apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config-app
    namespace: app
data:
  app.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /helloworld/ {
          proxy_pass   http://helloworld:8080/;
        }
    
        location /pki-validation/ {
          proxy_pass   http://pki-validation:80;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
