// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	epidemic_mobile "github.com/Baal19905/playground/go-zero/epidemic/api/internal/handler/epidemic_mobile"
	"github.com/Baal19905/playground/go-zero/epidemic/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/epidemic/msg-code",
				Handler: MsgCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/epidemic_mobile/user/find",
					Handler: epidemic_mobile.MobileUserFindHandler(serverCtx),
				},
			}...,
		),
	)
}
