apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: ccr.ccs.tencentyun.com/daihouda/helloworld:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
      - name: ccr.ccs.tencentyun.com
