// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMarketInfo = "market_infos"

// MarketInfo mapped from table <market_infos>
type MarketInfo struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TradeDate  string `gorm:"column:trade_date;not null" json:"trade_date"`
	MarketData string `gorm:"column:market_data" json:"market_data"`
	Type       int32  `gorm:"column:type" json:"type"`
}

// TableName MarketInfo's table name
func (*MarketInfo) TableName() string {
	return TableNameMarketInfo
}
