//*
// Copyright (C) 2015-2016，大连商品交易所 大连飞创信息技术有限公司
//
// @file
// @brief 运营管理平台proto定义
//
// @author <wyl>
//
// @date 2020-05-14
// @note 组内评审专家：todo
// @note 组外评审专家：todo
// @note
// @modify

//*
// 协议段使用规则
// service-omp： 31001~31999
//协议号书写规则
//OP_OMP_{请求REQ，响应RSP，推送RTN}_{具体业务协议名称}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: fip_const_omp.proto

package fippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol_OMP int32

const (
	Protocol_OMP_OPOMP_Begin Protocol_OMP = 0
	// ///////////////////////// 运营管理平台(OMP : Operation Management Platform)交互协议 //////////////////////////////
	Protocol_OMP_OP_OMP_REQ_SRV_REG  Protocol_OMP = 31001 ///< 应用服务注册请求
	Protocol_OMP_OP_OMP_RSP_SRV_REG  Protocol_OMP = 31002 ///< 应用服务注册应答
	Protocol_OMP_OP_OMP_REQ_COND_CMD Protocol_OMP = 31003 ///< 条件单操作请求
	Protocol_OMP_OP_OMP_RSP_COND_CMD Protocol_OMP = 31004 ///< 条件单操作处理结果
)

// Enum value maps for Protocol_OMP.
var (
	Protocol_OMP_name = map[int32]string{
		0:     "OPOMP_Begin",
		31001: "OP_OMP_REQ_SRV_REG",
		31002: "OP_OMP_RSP_SRV_REG",
		31003: "OP_OMP_REQ_COND_CMD",
		31004: "OP_OMP_RSP_COND_CMD",
	}
	Protocol_OMP_value = map[string]int32{
		"OPOMP_Begin":         0,
		"OP_OMP_REQ_SRV_REG":  31001,
		"OP_OMP_RSP_SRV_REG":  31002,
		"OP_OMP_REQ_COND_CMD": 31003,
		"OP_OMP_RSP_COND_CMD": 31004,
	}
)

func (x Protocol_OMP) Enum() *Protocol_OMP {
	p := new(Protocol_OMP)
	*p = x
	return p
}

func (x Protocol_OMP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol_OMP) Descriptor() protoreflect.EnumDescriptor {
	return file_fip_const_omp_proto_enumTypes[0].Descriptor()
}

func (Protocol_OMP) Type() protoreflect.EnumType {
	return &file_fip_const_omp_proto_enumTypes[0]
}

func (x Protocol_OMP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol_OMP.Descriptor instead.
func (Protocol_OMP) EnumDescriptor() ([]byte, []int) {
	return file_fip_const_omp_proto_rawDescGZIP(), []int{0}
}

var File_fip_const_omp_proto protoreflect.FileDescriptor

var file_fip_const_omp_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x5f, 0x6f, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x69, 0x70, 0x70, 0x62, 0x2a, 0x89, 0x01, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x4f, 0x4d, 0x50, 0x12, 0x0f, 0x0a,
	0x0b, 0x4f, 0x50, 0x4f, 0x4d, 0x50, 0x5f, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x18,
	0x0a, 0x12, 0x4f, 0x50, 0x5f, 0x4f, 0x4d, 0x50, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x53, 0x52, 0x56,
	0x5f, 0x52, 0x45, 0x47, 0x10, 0x99, 0xf2, 0x01, 0x12, 0x18, 0x0a, 0x12, 0x4f, 0x50, 0x5f, 0x4f,
	0x4d, 0x50, 0x5f, 0x52, 0x53, 0x50, 0x5f, 0x53, 0x52, 0x56, 0x5f, 0x52, 0x45, 0x47, 0x10, 0x9a,
	0xf2, 0x01, 0x12, 0x19, 0x0a, 0x13, 0x4f, 0x50, 0x5f, 0x4f, 0x4d, 0x50, 0x5f, 0x52, 0x45, 0x51,
	0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x9b, 0xf2, 0x01, 0x12, 0x19, 0x0a,
	0x13, 0x4f, 0x50, 0x5f, 0x4f, 0x4d, 0x50, 0x5f, 0x52, 0x53, 0x50, 0x5f, 0x43, 0x4f, 0x4e, 0x44,
	0x5f, 0x43, 0x4d, 0x44, 0x10, 0x9c, 0xf2, 0x01, 0x42, 0x1b, 0x5a, 0x19, 0x66, 0x69, 0x70, 0x64,
	0x65, 0x76, 0x2e, 0x64, 0x66, 0x69, 0x74, 0x63, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6e, 0x2f,
	0x66, 0x69, 0x70, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fip_const_omp_proto_rawDescOnce sync.Once
	file_fip_const_omp_proto_rawDescData = file_fip_const_omp_proto_rawDesc
)

func file_fip_const_omp_proto_rawDescGZIP() []byte {
	file_fip_const_omp_proto_rawDescOnce.Do(func() {
		file_fip_const_omp_proto_rawDescData = protoimpl.X.CompressGZIP(file_fip_const_omp_proto_rawDescData)
	})
	return file_fip_const_omp_proto_rawDescData
}

var file_fip_const_omp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fip_const_omp_proto_goTypes = []interface{}{
	(Protocol_OMP)(0), // 0: fippb.Protocol_OMP
}
var file_fip_const_omp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fip_const_omp_proto_init() }
func file_fip_const_omp_proto_init() {
	if File_fip_const_omp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fip_const_omp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fip_const_omp_proto_goTypes,
		DependencyIndexes: file_fip_const_omp_proto_depIdxs,
		EnumInfos:         file_fip_const_omp_proto_enumTypes,
	}.Build()
	File_fip_const_omp_proto = out.File
	file_fip_const_omp_proto_rawDesc = nil
	file_fip_const_omp_proto_goTypes = nil
	file_fip_const_omp_proto_depIdxs = nil
}
