//*
// Copyright (C) 2018-2019，大连商品交易所 大连飞创信息技术有限公司
//
// @file
// @brief 运营管理平台proto定义
//
// @author <wyl>
//
// @date 2020-05-14
// @note 组内评审专家：todo
// @note 组外评审专家：todo
// @note
// @modify

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: fip_def_omp.proto

package fippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ///////////////////////// 运营管理平台(OMP : Operation Management Platform)类型定义 //////////////////////////////
// /< 条件单操作类型
type EOMPCondCmd int32

const (
	EOMPCondCmd_OMPCC_Null   EOMPCondCmd = 0 ///< 开始标志
	EOMPCondCmd_OMPCC_Start  EOMPCondCmd = 1 ///< 启动
	EOMPCondCmd_OMPCC_Pause  EOMPCondCmd = 2 ///< 暂停
	EOMPCondCmd_OMPCC_Delete EOMPCondCmd = 3 ///< 删除
	EOMPCondCmd_OMPCC_End    EOMPCondCmd = 4 ///< 结束标志
)

// Enum value maps for EOMPCondCmd.
var (
	EOMPCondCmd_name = map[int32]string{
		0: "OMPCC_Null",
		1: "OMPCC_Start",
		2: "OMPCC_Pause",
		3: "OMPCC_Delete",
		4: "OMPCC_End",
	}
	EOMPCondCmd_value = map[string]int32{
		"OMPCC_Null":   0,
		"OMPCC_Start":  1,
		"OMPCC_Pause":  2,
		"OMPCC_Delete": 3,
		"OMPCC_End":    4,
	}
)

func (x EOMPCondCmd) Enum() *EOMPCondCmd {
	p := new(EOMPCondCmd)
	*p = x
	return p
}

func (x EOMPCondCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EOMPCondCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_fip_def_omp_proto_enumTypes[0].Descriptor()
}

func (EOMPCondCmd) Type() protoreflect.EnumType {
	return &file_fip_def_omp_proto_enumTypes[0]
}

func (x EOMPCondCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EOMPCondCmd.Descriptor instead.
func (EOMPCondCmd) EnumDescriptor() ([]byte, []int) {
	return file_fip_def_omp_proto_rawDescGZIP(), []int{0}
}

// /< 服务类型
type EServiceType int32

const (
	EServiceType_ST_Null      EServiceType = 0 ///< 开始标志
	EServiceType_ST_Cond_Mgr  EServiceType = 1 ///< 条件单服务
	EServiceType_ST_Trade_Srv EServiceType = 2 ///< 交易中继
	EServiceType_ST_End       EServiceType = 3 ///< 结束标志
)

// Enum value maps for EServiceType.
var (
	EServiceType_name = map[int32]string{
		0: "ST_Null",
		1: "ST_Cond_Mgr",
		2: "ST_Trade_Srv",
		3: "ST_End",
	}
	EServiceType_value = map[string]int32{
		"ST_Null":      0,
		"ST_Cond_Mgr":  1,
		"ST_Trade_Srv": 2,
		"ST_End":       3,
	}
)

func (x EServiceType) Enum() *EServiceType {
	p := new(EServiceType)
	*p = x
	return p
}

func (x EServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_fip_def_omp_proto_enumTypes[1].Descriptor()
}

func (EServiceType) Type() protoreflect.EnumType {
	return &file_fip_def_omp_proto_enumTypes[1]
}

func (x EServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EServiceType.Descriptor instead.
func (EServiceType) EnumDescriptor() ([]byte, []int) {
	return file_fip_def_omp_proto_rawDescGZIP(), []int{1}
}

var File_fip_def_omp_proto protoreflect.FileDescriptor

var file_fip_def_omp_proto_rawDesc = []byte{
	0x0a, 0x11, 0x66, 0x69, 0x70, 0x5f, 0x64, 0x65, 0x66, 0x5f, 0x6f, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x69, 0x70, 0x70, 0x62, 0x2a, 0x60, 0x0a, 0x0b, 0x45, 0x4f,
	0x4d, 0x50, 0x43, 0x6f, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x4d, 0x50,
	0x43, 0x43, 0x5f, 0x4e, 0x75, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x4d, 0x50,
	0x43, 0x43, 0x5f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x4d,
	0x50, 0x43, 0x43, 0x5f, 0x50, 0x61, 0x75, 0x73, 0x65, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4f,
	0x4d, 0x50, 0x43, 0x43, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0d, 0x0a,
	0x09, 0x4f, 0x4d, 0x50, 0x43, 0x43, 0x5f, 0x45, 0x6e, 0x64, 0x10, 0x04, 0x2a, 0x4a, 0x0a, 0x0c,
	0x45, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x54, 0x5f, 0x4e, 0x75, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x5f,
	0x43, 0x6f, 0x6e, 0x64, 0x5f, 0x4d, 0x67, 0x72, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54,
	0x5f, 0x54, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x53, 0x72, 0x76, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x54, 0x5f, 0x45, 0x6e, 0x64, 0x10, 0x03, 0x42, 0x1b, 0x5a, 0x19, 0x66, 0x69, 0x70, 0x64,
	0x65, 0x76, 0x2e, 0x64, 0x66, 0x69, 0x74, 0x63, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6e, 0x2f,
	0x66, 0x69, 0x70, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fip_def_omp_proto_rawDescOnce sync.Once
	file_fip_def_omp_proto_rawDescData = file_fip_def_omp_proto_rawDesc
)

func file_fip_def_omp_proto_rawDescGZIP() []byte {
	file_fip_def_omp_proto_rawDescOnce.Do(func() {
		file_fip_def_omp_proto_rawDescData = protoimpl.X.CompressGZIP(file_fip_def_omp_proto_rawDescData)
	})
	return file_fip_def_omp_proto_rawDescData
}

var file_fip_def_omp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fip_def_omp_proto_goTypes = []interface{}{
	(EOMPCondCmd)(0),  // 0: fippb.EOMPCondCmd
	(EServiceType)(0), // 1: fippb.EServiceType
}
var file_fip_def_omp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fip_def_omp_proto_init() }
func file_fip_def_omp_proto_init() {
	if File_fip_def_omp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fip_def_omp_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fip_def_omp_proto_goTypes,
		DependencyIndexes: file_fip_def_omp_proto_depIdxs,
		EnumInfos:         file_fip_def_omp_proto_enumTypes,
	}.Build()
	File_fip_def_omp_proto = out.File
	file_fip_def_omp_proto_rawDesc = nil
	file_fip_def_omp_proto_goTypes = nil
	file_fip_def_omp_proto_depIdxs = nil
}
