// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package msgcode

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC803d3e7DecodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode(in *jlexer.Lexer, out *Freeze) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "expire_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ExpireAt).UnmarshalJSON(data))
			}
		case "window":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Window).UnmarshalJSON(data))
			}
		case "count":
			out.Count = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC803d3e7EncodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode(out *jwriter.Writer, in Freeze) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"expire_at\":"
		out.RawString(prefix[1:])
		out.Raw((in.ExpireAt).MarshalJSON())
	}
	{
		const prefix string = ",\"window\":"
		out.RawString(prefix)
		out.Raw((in.Window).MarshalJSON())
	}
	{
		const prefix string = ",\"count\":"
		out.RawString(prefix)
		out.Int(int(in.Count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Freeze) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC803d3e7EncodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Freeze) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC803d3e7EncodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Freeze) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC803d3e7DecodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Freeze) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC803d3e7DecodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode(l, v)
}
func easyjsonC803d3e7DecodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode1(in *jlexer.Lexer, out *Code) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = string(in.String())
		case "wrong":
			out.Wrong = int(in.Int())
		case "expire_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ExpireAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC803d3e7EncodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode1(out *jwriter.Writer, in Code) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"wrong\":"
		out.RawString(prefix)
		out.Int(int(in.Wrong))
	}
	{
		const prefix string = ",\"expire_at\":"
		out.RawString(prefix)
		out.Raw((in.ExpireAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Code) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC803d3e7EncodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Code) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC803d3e7EncodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Code) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC803d3e7DecodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Code) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC803d3e7DecodeGithubComforestycPlaygroundGoZeroEpidemicPkgMsgcode1(l, v)
}
