// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEpidemicInterfaceAuth = "epidemic_interface_auth"

// EpidemicInterfaceAuth mapped from table <epidemic_interface_auth>
type EpidemicInterfaceAuth struct {
	ID        int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	AppKey    string `gorm:"column:app_key;type:varchar(100);not null;uniqueIndex:app_key,priority:1" json:"app_key"`
	AppSecret string `gorm:"column:app_secret;type:varchar(100);not null;uniqueIndex:app_secret,priority:1" json:"app_secret"`
}

// TableName EpidemicInterfaceAuth's table name
func (*EpidemicInterfaceAuth) TableName() string {
	return TableNameEpidemicInterfaceAuth
}
