// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEpidemicDictionaryDetail = "epidemic_dictionary_detail"

// EpidemicDictionaryDetail mapped from table <epidemic_dictionary_detail>
type EpidemicDictionaryDetail struct {
	ID    int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Key   string `gorm:"column:key;type:varchar(100);not null;index:epidemic_dictionary_detail_uqidx1,priority:1" json:"key"`   // 功能
	Name  string `gorm:"column:name;type:varchar(100);not null;index:epidemic_dictionary_detail_uqidx1,priority:2" json:"name"` // 字典key
	Value string `gorm:"column:value;type:varchar(100);not null" json:"value"`                                                  // 字典value
}

// TableName EpidemicDictionaryDetail's table name
func (*EpidemicDictionaryDetail) TableName() string {
	return TableNameEpidemicDictionaryDetail
}
