// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEpidemicRelatedStaff = "epidemic_related_staff"

// EpidemicRelatedStaff mapped from table <epidemic_related_staff>
type EpidemicRelatedStaff struct {
	ID                    int32          `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Mobile                string         `gorm:"column:mobile;type:varchar(20);not null;uniqueIndex:epidemic_related_staff_uqidx1,priority:1" json:"mobile"` // 手机号
	Name                  []byte         `gorm:"column:name;type:varbinary(500)" json:"name"`
	Company               string         `gorm:"column:company;type:varchar(50);not null" json:"company"`               // 公司：字典值
	Department            string         `gorm:"column:department;type:varchar(50);not null" json:"department"`         // 部门：字典值
	Organization          string         `gorm:"column:organization;type:varchar(50);not null" json:"organization"`     // 编制：字典值
	Location              string         `gorm:"column:location;type:varchar(50);not null" json:"location"`             // 工作地点：字典值
	AppletReport          string         `gorm:"column:applet_report;type:varchar(50);not null" json:"applet_report"`   // 是否上传小程序：字典值
	IsolationType         string         `gorm:"column:isolation_type;type:varchar(50);not null" json:"isolation_type"` // 隔离情况分类：字典值
	Region                []byte         `gorm:"column:region;type:varbinary(500)" json:"region"`
	ResidentialAddress    []byte         `gorm:"column:residential_address;type:varbinary(500)" json:"residential_address"`
	Community             string         `gorm:"column:community;type:varchar(200);not null" json:"community"`                  // 所属社区
	CommunityTel          string         `gorm:"column:community_tel;type:varchar(32);not null" json:"community_tel"`           // 社区电话
	Street                string         `gorm:"column:street;type:varchar(200);not null" json:"street"`                        // 所属街道
	Description           string         `gorm:"column:description;type:varchar(200);not null" json:"description"`              // 情况描述
	CommunityRequirements string         `gorm:"column:community_requirements;type:varchar(200)" json:"community_requirements"` // 情况描述
	NucleicAcidRecord     string         `gorm:"column:nucleic_acid_record;type:text;not null" json:"nucleic_acid_record"`      // 核酸记录
	TemperatureRecord     string         `gorm:"column:temperature_record;type:text;not null" json:"temperature_record"`        // 体温记录
	HomeBeginDate         time.Time      `gorm:"column:home_begin_date;type:date;not null" json:"home_begin_date"`              // 居家开始时间
	ReturnDate            time.Time      `gorm:"column:return_date;type:date" json:"return_date"`                               // 返岗时间
	ReportDate            time.Time      `gorm:"column:report_date;type:datetime(3)" json:"report_date"`                        // 填报日期
	ReportedBy            string         `gorm:"column:reported_by;type:varchar(50);not null" json:"reported_by"`               // 填报人
	CreatedAt             time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt             time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt             gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_epidemic_related_staff_deleted_at,priority:1" json:"deleted_at"`
	RegionName            []byte         `gorm:"column:region_name;type:varbinary(500)" json:"region_name"`
	CompanyOaDate         time.Time      `gorm:"column:company_oa_date;type:date" json:"company_oa_date"`
}

// TableName EpidemicRelatedStaff's table name
func (*EpidemicRelatedStaff) TableName() string {
	return TableNameEpidemicRelatedStaff
}
