// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEpidemicInvestigationDetail = "epidemic_investigation_details"

// EpidemicInvestigationDetail mapped from table <epidemic_investigation_details>
type EpidemicInvestigationDetail struct {
	ID               int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	RelatedFormID    int32     `gorm:"column:related_form_id;type:int" json:"related_form_id"`    // 关联疫情筛查表id
	Status           string    `gorm:"column:status;type:varchar(50);not null" json:"status"`     // 登记状态：字典值
	Abnormal         string    `gorm:"column:abnormal;type:varchar(50);not null" json:"abnormal"` // 是否异常
	Remarks          string    `gorm:"column:remarks;type:varchar(191)" json:"remarks"`           // 备注
	ReporteTime      time.Time `gorm:"column:reporte_time;type:datetime(3)" json:"reporte_time"`  // 上报时间
	UpdateTime       time.Time `gorm:"column:update_time;type:datetime(3)" json:"update_time"`    // 更新时间
	FormStatus       string    `gorm:"column:form_status;type:varchar(50)" json:"form_status"`    // 筛查表状态
	Mobile           string    `gorm:"column:mobile;type:varchar(20)" json:"mobile"`              // 手机号
	Answer           string    `gorm:"column:answer;type:varchar(200)" json:"answer"`
	SpecialSituation string    `gorm:"column:special_situation;type:varchar(200)" json:"special_situation"`
}

// TableName EpidemicInvestigationDetail's table name
func (*EpidemicInvestigationDetail) TableName() string {
	return TableNameEpidemicInvestigationDetail
}
