// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEpidemicTemplate = "epidemic_templates"

// EpidemicTemplate mapped from table <epidemic_templates>
type EpidemicTemplate struct {
	ID     int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name   string `gorm:"column:name;type:varchar(50)" json:"name"` // 名字
	Link   string `gorm:"column:link;type:varchar(50)" json:"link"` // 连接地址
	Remark string `gorm:"column:remark;type:text" json:"remark"`    // 备注
}

// TableName EpidemicTemplate's table name
func (*EpidemicTemplate) TableName() string {
	return TableNameEpidemicTemplate
}
