// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEpidemicInvestigationForm = "epidemic_investigation_form"

// EpidemicInvestigationForm mapped from table <epidemic_investigation_form>
type EpidemicInvestigationForm struct {
	ID           int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Title        string    `gorm:"column:title;type:varchar(100);not null" json:"title"` // 筛查表标题
	Content      string    `gorm:"column:content;type:text" json:"content"`
	Link         string    `gorm:"column:link;type:varchar(200)" json:"link"`                         // 附件下载链接
	Questions    string    `gorm:"column:questions;type:varchar(500);not null" json:"questions"`      // json,允许多个问题对，问题对包括问题、判定标准
	Status       string    `gorm:"column:status;type:varchar(50);not null" json:"status"`             // 状态：字典值
	Abnormal     int32     `gorm:"column:abnormal;type:int" json:"abnormal"`                          // 异常统计
	Company      string    `gorm:"column:company;type:varchar(50);not null" json:"company"`           // 公司
	Department   string    `gorm:"column:department;type:varchar(50);not null" json:"department"`     // 部门
	Organization string    `gorm:"column:organization;type:varchar(50);not null" json:"organization"` // 编制
	Location     string    `gorm:"column:location;type:varchar(50);not null" json:"location"`         // 工作地
	PublishedBy  string    `gorm:"column:published_by;type:varchar(50);not null" json:"published_by"` // 发布者
	PublishDate  time.Time `gorm:"column:publish_date;type:datetime(6);not null" json:"publish_date"` // 发布时间
	URLLink      string    `gorm:"column:url_link;type:text" json:"url_link"`
}

// TableName EpidemicInvestigationForm's table name
func (*EpidemicInvestigationForm) TableName() string {
	return TableNameEpidemicInvestigationForm
}
