// Code generated by goctl. DO NOT EDIT.
package types

type CommonMsgCodeReq struct {
	Mobile string `form:"mobile"`
}

type CommonMsgCodeResp struct {
	Message string `json:"message"`
}

type LoginReq struct {
	Mobile string `form:"mobile"`
	Device string `form:"device,optional"`
	Code   string `form:"code""`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type LoginResp struct {
	Message string `json:"message"`
	Data    Token  `json:"data"`
}

type MobileUserFindResp struct {
	ID                       int    `json:"id"`
	Name                     string `json:"name"`
	Sex                      string `json:"sex"`
	Mobile                   string `json:"mobile"`
	BirthDate                string `json:"birthDate"`
	Company                  string `json:"company"`
	Department               string `json:"department"`
	Organization             string `json:"organization"`
	Location                 string `json:"location"`
	ResidentialAddressCode   string `json:"residentialAddressCode"`
	ResidentialAddressName   string `json:"residentialAddressName"`
	ResidentialAddressDetail string `json:"residentialAddressDetail"`
	VaccinationRecord        string `json:"vaccinationRecord"`
	VaccinationTime          string `json:"vaccinationTime"`
	ReasonForNonVaccination  string `json:"reasonForNonVaccination"`
	Role                     string `json:"role"`
	Status                   string `json:"status"`
	ApprovedBy               string `json:"approvedBy"`
	ApprovalComments         string `json:"approvalComments"`
	ApprovalDate             string `json:"approvalDate"`
	Label                    string `json:"label"`
}
